name: ChunkyProtections
main: org.getchunky.chunkyprotections.ChunkyProtections
version: b${build.number}
author: dumptruckman

depend: [Chunky]

permissions:
    chunky.grief.creeper:
        description: Prevents creepers from destroying blocks when targeting someone without appropriate destroy permissions.
        default: op
    chunky.grief.tnt.ignore:
        description: Allows a user to ignore tnt restriction set in config.yml
        default: op
        